FROM debian:buster

WORKDIR /tmp

# Install dependencies
RUN apt-get update && apt install -y curl wget build-essential zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev

# Install python
RUN wget https://www.python.org/ftp/python/3.7.4/Python-3.7.4.tgz \
 && tar -xf Python-3.7.4.tgz \
 && cd Python-3.7.4 \
 && ./configure --enable-optimizations \
 && make install \
 && python3 --version

# Install pip
RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py \
 && python3 get-pip.py